"""
Creative Assets Router — Zero-Leak Remote Asset Streaming & Ephemeral URL Signing for DM AI OS v1.5.1.
Enables secure, authenticated access to vaulted media (images/videos) generated by CreativeEngine.
Uses HMAC-SHA256 presigned URLs ensuring zero master API Key exposure and single-asset cryptographic binding.
"""
import os
import time
import hmac
import hashlib
import mimetypes
import logging
from pathlib import Path
from typing import Dict, Any, Optional

from fastapi import APIRouter, Depends, HTTPException, Query, Request, Security
from fastapi.responses import FileResponse, JSONResponse

from ..storage.storage_layer import storage
from .auth import verify_api_key

log = logging.getLogger("creative_assets_router")

creative_assets_router = APIRouter(prefix="/api/v1/creative/assets", tags=["Creative Assets"])

# ─── Configuration & Key Resolution ──────────────────────────────────────────

def get_signing_secret() -> bytes:
    """
    Retrieves the HMAC signing secret from environment.
    Strict safety: Fails explicitly with HTTP 500 if unconfigured (no insecure hardcoded fallbacks).
    """
    secret = os.getenv("DM_MEDIA_SIGNING_SECRET")
    if not secret or not secret.strip():
        log.error("[CreativeAssets] DM_MEDIA_SIGNING_SECRET is not configured on the server.")
        raise HTTPException(
            status_code=500,
            detail="Media signing secret (DM_MEDIA_SIGNING_SECRET) is not configured on the server."
        )
    return secret.strip().encode("utf-8")


def get_default_ttl() -> int:
    """Returns default URL time-to-live in seconds (default: 1800s / 30 mins)."""
    try:
        return max(10, int(os.getenv("DM_MEDIA_URL_TTL_SEC", "1800")))
    except Exception:
        return 1800


# ─── Cryptographic Signing & Verification ────────────────────────────────────

def generate_signed_urls(job_id: str, ttl: Optional[int] = None, base_url: str = "") -> Dict[str, Any]:
    """
    Generates HMAC-SHA256 presigned URLs for viewing and downloading a specific job's media asset.
    The signature is cryptographically bound to (job_id + exp + action).
    """
    secret = get_signing_secret()
    ttl_sec = max(10, int(ttl or get_default_ttl()))
    exp = int(time.time()) + ttl_sec

    # Action-specific payloads
    payload_view = f"{job_id}:{exp}:view".encode("utf-8")
    payload_dl = f"{job_id}:{exp}:download".encode("utf-8")

    sig_view = hmac.new(secret, payload_view, hashlib.sha256).hexdigest()
    sig_dl = hmac.new(secret, payload_dl, hashlib.sha256).hexdigest()

    clean_base = base_url.rstrip("/")
    return {
        "job_id": job_id,
        "expires_at": exp,
        "ttl_seconds": ttl_sec,
        "view_url": f"{clean_base}/api/v1/creative/assets/{job_id}/view?exp={exp}&sig={sig_view}",
        "download_url": f"{clean_base}/api/v1/creative/assets/{job_id}/download?exp={exp}&sig={sig_dl}"
    }


def verify_asset_signature(job_id: str, action: str, exp: int, signature: str) -> None:
    """
    Validates HMAC signature authenticity and expiration timestamp in constant time.
    Raises HTTP 403 upon expiration, tampering, or mismatched action/job_id.
    """
    # 1. Expiration check
    current_time = int(time.time())
    if current_time > exp:
        log.warning(f"[CreativeAssets] Expired asset URL accessed for job '{job_id}' (exp: {exp}, now: {current_time})")
        raise HTTPException(status_code=403, detail="Signed asset URL has expired.")

    # 2. Signature verification
    secret = get_signing_secret()
    expected_payload = f"{job_id}:{exp}:{action}".encode("utf-8")
    expected_sig = hmac.new(secret, expected_payload, hashlib.sha256).hexdigest()

    if not hmac.compare_digest(signature.lower(), expected_sig.lower()):
        log.warning(f"[CreativeAssets] Invalid signature for job '{job_id}' and action '{action}'")
        raise HTTPException(status_code=403, detail="Invalid signature for this asset or action.")


# ─── Path Resolution & Traversal Prevention ──────────────────────────────────

def resolve_vault_file(job_id: str) -> Path:
    """
    Resolves the physical file on disk for a job from JobStore.
    Guarantees strict confinement within Project_State/Artifacts/media/ preventing path traversal.
    """
    job = storage.job_store.get_job(job_id)
    if not job:
        raise HTTPException(status_code=404, detail=f"Creative job '{job_id}' not found.")

    if job.get("status") != "COMPLETED":
        raise HTTPException(
            status_code=400,
            detail=f"Job '{job_id}' is not COMPLETED (current status: {job.get('status')})."
        )

    output_assets = job.get("output_assets", [])
    if not output_assets:
        raise HTTPException(status_code=404, detail=f"No output media assets recorded for job '{job_id}'.")

    # Vault base directory
    project_state_dir = Path("Project_State").resolve()
    media_vault_root = (project_state_dir / "Artifacts" / "media").resolve()

    # Relative asset path from job record (e.g. Artifacts/media/<job_id>/<file>.png)
    asset_rel = output_assets[0]
    target_path = (project_state_dir / asset_rel).resolve()

    # Confinement assertion
    try:
        target_path.relative_to(media_vault_root)
    except ValueError:
        log.error(f"[CreativeAssets] Path traversal attempt detected: '{target_path}' outside '{media_vault_root}'")
        raise HTTPException(status_code=403, detail="Access denied: Asset path is outside the media vault.")

    if not target_path.is_file():
        log.error(f"[CreativeAssets] Physical file missing from disk: '{target_path}'")
        raise HTTPException(status_code=404, detail="Physical media file not found on disk.")

    return target_path


# ─── API Endpoints ────────────────────────────────────────────────────────────

@creative_assets_router.post("/{job_id}/sign", dependencies=[Depends(verify_api_key)])
async def sign_asset_url(
    job_id: str,
    request: Request,
    ttl: Optional[int] = Query(None, description="Custom TTL in seconds")
):
    """
    Generates fresh HMAC-SHA256 presigned URLs for viewing and downloading a generated asset.
    Requires authenticated API Key or User Token.
    """
    # Verify job exists and is completed
    resolve_vault_file(job_id)
    base_url = str(request.base_url).rstrip("/")
    signed = generate_signed_urls(job_id=job_id, ttl=ttl, base_url=base_url)
    return JSONResponse(content={"status": "SUCCESS", **signed})


@creative_assets_router.get("/{job_id}/metadata", dependencies=[Depends(verify_api_key)])
async def get_asset_metadata(job_id: str, request: Request):
    """
    Returns complete technical metadata, cryptographic SHA-256, and freshly signed URLs.
    Requires authenticated API Key or User Token.
    """
    file_path = resolve_vault_file(job_id)
    job = storage.job_store.get_job(job_id)
    base_url = str(request.base_url).rstrip("/")
    signed = generate_signed_urls(job_id=job_id, base_url=base_url)

    mime_type, _ = mimetypes.guess_type(str(file_path))
    return JSONResponse(content={
        "status": "SUCCESS",
        "job_id": job_id,
        "filename": file_path.name,
        "media_type": mime_type or "image/png",
        "size_bytes": file_path.stat().st_size,
        "sha256": job.get("output_sha256"),
        "workflow_name": job.get("workflow_name"),
        "model_checkpoint": job.get("model_checkpoint"),
        "prompt": job.get("prompt"),
        "created_at": job.get("created_at"),
        "completed_at": job.get("completed_at"),
        "urls": signed
    })


@creative_assets_router.get("/{job_id}/view")
async def view_asset_inline(
    job_id: str,
    exp: int = Query(..., description="Expiration timestamp"),
    sig: str = Query(..., description="HMAC-SHA256 signature")
):
    """
    Streams the media asset inline for <img> tags and browser preview.
    Validated entirely via HMAC signature without exposing master API Key.
    """
    verify_asset_signature(job_id=job_id, action="view", exp=exp, signature=sig)
    file_path = resolve_vault_file(job_id)

    mime_type, _ = mimetypes.guess_type(str(file_path))
    clean_mime = mime_type or "image/png"

    return FileResponse(
        path=str(file_path),
        media_type=clean_mime,
        headers={
            "Content-Disposition": f'inline; filename="{file_path.name}"',
            "Cache-Control": "public, max-age=31536000, immutable"
        }
    )


@creative_assets_router.get("/{job_id}/download")
async def download_asset_attachment(
    job_id: str,
    exp: int = Query(..., description="Expiration timestamp"),
    sig: str = Query(..., description="HMAC-SHA256 signature")
):
    """
    Streams the media asset with attachment header for forced browser download on mobile and desktop.
    Validated entirely via HMAC signature without exposing master API Key.
    """
    verify_asset_signature(job_id=job_id, action="download", exp=exp, signature=sig)
    file_path = resolve_vault_file(job_id)

    mime_type, _ = mimetypes.guess_type(str(file_path))
    clean_mime = mime_type or "application/octet-stream"

    return FileResponse(
        path=str(file_path),
        media_type=clean_mime,
        headers={
            "Content-Disposition": f'attachment; filename="{file_path.name}"',
            "Cache-Control": "no-cache"
        }
    )
